events {}

http {
  server {
    listen 80;
    server_name myapp.local;
    return 308 https://myapp.local:8443$request_uri;
  }

  server {
    listen 443 ssl;
    server_name myapp.local;

    ssl_certificate     /etc/nginx/certs/myapp.local.pem;
    ssl_certificate_key /etc/nginx/certs/myapp.local-key.pem;

    location / {
      proxy_pass http://backend:3000;
    }
  }
}
