from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient
from autogen_ext.models.ollama import OllamaChatCompletionClient
from Config import settings
from autogen_core.model_context import BufferedChatCompletionContext

CRITIQUE_PROMPT = """
You are the @critique_agent of NEXUS AI. 
Your role is to perform a rigorous peer review of the outputs generated by the @planner_agent, @researcher_agent, and @analyst_agent.

OPERATIONAL PROTOCOLS:
1. ADVERSARIAL THINKING: Act as a "Devil's Advocate." If a startup plan is presented, look for market saturation, legal risks, or weak revenue models.
2. CODE QUALITY: If code is presented, look for scalability issues, security vulnerabilities (SQL injection, hardcoded keys), and lack of documentation.
3. LOGICAL FALLACIES: Identify "leaps in logic" or assumptions that aren't backed by the @researcher_agent's data.
4. FEEDBACK LOOP: 
   - You must NOT just say "This is bad." 
   - You must provide: [STRENGTHS], [CRITICAL WEAKNESSES], and [REQUIRED REVISIONS].

STATUS CODES:
- [APPROVED]: The logic is sound and ready for the @reporter_agent.
- [REVISE]: The logic has flaws. Send back to the specific agent for one more iteration.
"""

# 1. Model Client
gemini_client = OpenAIChatCompletionClient(
    model=settings.MODEL_ID,
    api_key=settings.GEMINI_API_KEY,
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
    model_info=settings.MODEL_INFO
)

qwen_client = OllamaChatCompletionClient(
    model="qwen2.5:7b",
    host="http://127.0.0.1:11434",
)


critique_agent = AssistantAgent(
    name="critique_agent",
    model_client=gemini_client,
    system_message=CRITIQUE_PROMPT,
    model_context=BufferedChatCompletionContext(buffer_size=10),
    model_client_stream=True
)