events {}

http {

  upstream backend_pool {
    server backend1:3000;
    server backend2:3000;
  }

  server {
    listen 8080;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;

    ssl_certificate /certs/app.pem;
    ssl_certificate_key /certs/app-key.pem;

    # Frontend (Next.js)
    location / {
      proxy_pass http://frontend:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Backend APIs
    location /api {
      proxy_pass http://backend_pool;
    }
  }
}
